spring.datasource.url: jdbc:h2:file:./target/h2db
spring.datasource.username: sa
spring.datasource.password: password

spring.datasource.driverClassName: org.h2.Driver
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

status:
  version: dev
