spring.datasource.url: jdbc:postgresql://localhost:5432/wallet
spring.datasource.username: klukashin
spring.datasource.password: 123

spring.jpa.generate-ddl: true
spring.session.jdbc.initialize-schema: always

spring.jpa.properties.hibernate.show_sql: true
spring.jpa.properties.hibernate.use_sql_comments: true
spring.jpa.properties.hibernate.format_sql: true

server.port: 9000
